name:                crypto-orderbook-db
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/runeksvendsen/crypto-orderbook-db#readme
license:             BSD3
author:              Rune K. Svendsen
maintainer:          runesvend@gmail.com
copyright:           CC0
category:            value
extra-source-files:
- README.md

dependencies:
  - base

ghc-options:
  - -Wall
  - -fno-warn-name-shadowing

default-extensions:
  - TypeFamilies

library:
  source-dirs: src
  other-modules:
  - CryptoDepth.OrderBook.Db.Internal.Prelude
  dependencies:
  - protolude
  - text
  - time
  - orderbook
  - safe-money
  - beam-core
  - beam-migrate
  - beam-postgres
  - vector
  - postgresql-transactional
  - postgresql-simple
  - transformers
  - logging
  - pretty-simple
  - containers  # Util
  default-extensions:
  - StandaloneDeriving
  - RecordWildCards
  - FlexibleInstances
  - DeriveGeneric
  - MultiParamTypeClasses
  - FlexibleContexts
  - ScopedTypeVariables

tests:
  crypto-orderbook-db-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - crypto-orderbook-db
    - hspec
    - random-shuffle
    - hspec-expectations
    - hspec-expectations-pretty-diff
