name:                crypto-orderbook-db
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/runeksvendsen/crypto-orderbook-db#readme
license:             BSD3
author:              Rune K. Svendsen
maintainer:          runesvend@gmail.com
copyright:           CC0
category:            value
extra-source-files:
- README.md

default-extensions:
- StandaloneDeriving
- RecordWildCards
- TypeFamilies
- FlexibleInstances
- DeriveGeneric
- MultiParamTypeClasses
- FlexibleContexts

dependencies:
  - base

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -fno-warn-name-shadowing
  other-modules:
  - CryptoDepth.OrderBook.Db.Internal.Prelude
  - CryptoDepth.OrderBook.Db.Internal.Util
  dependencies:
  - text
  - time
  - orderbook
  - beam-core
  - beam-migrate
  - beam-postgres


executables:
  crypto-orderbook-db:
    source-dirs:      app
    main:             Main.hs
