name:                crypto-orderbook-db
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/runeksvendsen/crypto-orderbook-db#readme
license:             BSD3
author:              Rune K. Svendsen
maintainer:          runesvend@gmail.com
copyright:           CC0
category:            value
extra-source-files:
- README.md

dependencies:
  - base

ghc-options:
  - -Wall
  - -fno-warn-name-shadowing

default-extensions:
  - TypeFamilies

library:
  source-dirs: src
  other-modules:
  - CryptoDepth.OrderBook.Db.Internal.Prelude
  dependencies:
  - protolude
  - text
  - time
  - orderbook
  - safe-money
  - beam-core
  - beam-migrate
  - beam-postgres
  - vector
  - postgresql-transactional
  - postgresql-simple
  - transformers
  - logging
  - pretty-simple
  - containers  # Util
  default-extensions:
  - StandaloneDeriving
  - RecordWildCards
  - FlexibleInstances
  - DeriveGeneric
  - MultiParamTypeClasses
  - FlexibleContexts
  - ScopedTypeVariables

executables:
  crypto-orderbook-db:
    source-dirs:      exe/app
    main:             Main.hs
    dependencies:
    - protolude
    - crypto-orderbook-db
    - orderbook
    - beam-postgres
    - optparse-applicative
    - postgresql-transactional
    - crypto-venues
    - monad-parallel
    - errors
    - logging
    - http-client
    - http-client-tls
    - text
    - bytestring
    - time
    - time-units  # Schedule
    - random      # Schedule
    - retry       # PqConnection
    - rate-limit  # RetrySimple
    - mtl         # RetrySimple
    - githash
    default-extensions:
    - RecordWildCards
  crypto-orderbook-db-create-tables:
    source-dirs:      exe/create-tables
    main:             Main.hs
    dependencies:
    - crypto-orderbook-db
    - beam-postgres
    - beam-migrate
    - optparse-applicative
    - bytestring
    - logging


tests:
  crypto-orderbook-db-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - crypto-orderbook-db
    - hspec
    - random-shuffle
    - hspec-expectations
    - hspec-expectations-pretty-diff
