name:                crypto-orderbook-db
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/runeksvendsen/crypto-orderbook-db#readme
license:             BSD3
author:              Rune K. Svendsen
maintainer:          runesvend@gmail.com
copyright:           CC0
category:            value
extra-source-files:
- README.md

dependencies:
  - base

ghc-options:
  - -Wall
  - -fno-warn-name-shadowing

library:
  source-dirs: src
  other-modules:
  - CryptoDepth.OrderBook.Db.Internal.Prelude
  - CryptoDepth.OrderBook.Db.Internal.Util
  dependencies:
  - protolude
  - text
  - time
  - orderbook
  - safe-money
  - beam-core
  - beam-migrate
  - beam-postgres
  - vector
  - postgresql-transactional
  - postgresql-simple
  - transformers
  - logging
  - pretty-simple
  default-extensions:
  - StandaloneDeriving
  - RecordWildCards
  - TypeFamilies
  - FlexibleInstances
  - DeriveGeneric
  - MultiParamTypeClasses
  - FlexibleContexts
  - ScopedTypeVariables

executables:
  crypto-orderbook-db:
    source-dirs:      exe/app
    main:             Main.hs
    dependencies:
    - protolude
    - crypto-orderbook-db
    - orderbook
    - beam-postgres
    - optparse-applicative
    - postgresql-transactional
    - crypto-venues
    - monad-parallel
    - errors
    - logging
    - http-client
    - http-client-tls
    - text
    - bytestring
    - time
  crypto-orderbook-db-create-tables:
    source-dirs:      exe/create-tables
    main:             Main.hs
    dependencies:
    - crypto-orderbook-db
    - beam-postgres
    - beam-migrate
    - optparse-applicative
    - bytestring
    - logging
